### ISSUE TITLE
Strong name issue

### ISSUE THREAD

**Issue by induster** [LitleCo/litle-sdk-for-dotNet#36]
Since FTP support was added (Tamir.SharpSsh) I was having a problem strong naming the sdk. Tamir.SharpSsh also has dependencies that require strong names as well. It was a bit of a rabbit hole acquiring the source code for all of these projects in order to rebuild using a strong name.

**Comment by brianarnold789** [comment]
master branch has been updated to include a signed Tamir.SharpSH implementation and we are now signing our releases going forward
