### ISSUE TITLE
Batch Calls - any chance you will add functionality to send batch requests?

### ISSUE THREAD

**Issue by ainsleyh** [LitleCo/litle-sdk-for-dotNet#38]
We are hoping to continue to use your sdk, but in the future we will need batch requests functionality support with Vantiv api. Any future plans to support this functionality?

**Comment by brianarnold789** [comment]
Which Vantiv API are you referring to? The current SDK implementation does support the Vantiv eCommerce (formerly Litle) batch API

**Comment by ainsleyh** [comment]
Nice! But if I wanted to batch 2 authorizations in one call, It looks like with the sdk the only way to authorize would be _litleClient.Authorize(authorization) which only accepts one authorization. Maybe I missing something?

**Comment by brianarnold789** [comment]
An example can be found in [TestBatch.cs](https://github.com/LitleCo/litle-sdk-for-dotNet/blob/master/LitleSdkForNet/LitleSdkForNetTest/Functional/TestBatch.cs). For a batch request you will need to create a ```litleRequest``` and a ```batchRequest```. Then add the add your transactions to the ```batchRequest``` and add the ```batchRequest``` to the ```litleRequest``` and call ```litleRequest.sendToLitle()```. To retrieve a batch, a use the batch name returned from the send call. ```litleRequest.blockAndWaitForResponse(BATCH_NAME)```

For more assistance please email sdksupport@vantiv.com

**Comment by ainsleyh** [comment]
I'll check it out - thanks!
