### ISSUE TITLE
Nuget Package very out of date (57 commits behind Master)

### ISSUE THREAD

**Issue by ainsleyh** [LitleCo/litle-sdk-for-dotNet#39]
The latest nuget in the package gallery is from April 9th. 
version: 9.3.2
commit: 5d17fff

There is a tagged release from Jul 29th version 9.3.3 which is pretty close to master but it is not available in the nuget package store.

I'm having issues with the current version of the nuget (9.3.2) rather than if I add a project reference to the latest version of your LitleVersionForNet. It looks like some key code is missing in the nuget that was added after April.

**Comment by brianarnold789** [comment]
The current package on is not maintained by Vantiv, this is why the release is not current. We can add the creation and maintenance of a Vantiv eCommerce NuGet package to our backlog.

**Comment by brianarnold789** [comment]
We have created a nuget package that will be managed by Vantiv eCommerce going forward
https://www.nuget.org/packages/Vantiv.LitleSdkForNet/
