### ISSUE TITLE
Issue with batch processing.

### ISSUE THREAD

**Issue by nitin16** [LitleCo/litle-sdk-for-dotNet#40]
I am trying to process batch transactions on Pre-live enviornment. I confirmed with Litle that account is set up for SFTP and veriffied user name and password. When I try to use SDK I get following exception. 

Is there any step I am missing? do I need client certificate?

UnknownHostKey: prelive.litle.com. RSA key fingerprint is bc:c7:58:00:0e:9......

Stack trace:
   at Tamir.SharpSsh.jsch.Session.connect(Int32 connectTimeout)
   at Tamir.SharpSsh.jsch.Session.connect()
   at Litle.Sdk.Communications.FtpDropOff(String fileDirectory, String fileName, Dictionary`2 config) in c:\Users\nbafna\Source\Repos\utilitles\LitleSdkForNet\LitleSdkForNet\Communications.cs:line 264

Thanks in advance for your help.

**Comment by brianarnold789** [comment]
Hi,
To establish an sFTP connection you will need a knownhosts file in the configured location containing the rsa fingerprint of our sFTP server. The contents should be the same as [this file](https://github.com/LitleCo/litle-sdk-for-dotNet/blob/master/LitleSdkForNet/LitleSdkForNet/knownhosts).
If you are still encountering connection issues please contact sdksupport@vantiv.com

**Comment by nitin16** [comment]
Thanks for quick reply. 
I still get same error. I will email SDK support.
