### ISSUE TITLE
litle-sdk Not Compitable with .Net Core 1.1

### ISSUE THREAD

**Issue by chandratokachichu** [LitleCo/litle-sdk-for-dotNet#45]
We have been using payment hub for a while and wanted to move to vantiv and this issue is blocking us to proceed further. 

1. Enums doesnot work at runtime (Country , CardType are throwing some errors) , the API throws a 500. 
2. Even after that the sdk throws some erros while used on .net core project

**Comment by brianarnold789** [comment]
Hi @chandratokachichu 
What exactly is throwing the error with the Country and CardType Enums? Is this an HTTP 500 error from the target server? Is there a stacktrace associated with the error? To which environment are you trying to send transactions (prelive, Sandbox, etc...)?

We have not tested the SDK against .NET Core. Our testing is completed against .NET 4.0 and 4.5

If you have further questions please email sdksupport@vantiv.com

**Comment by chandratokachichu** [comment]
@brianarnold789 - Http 500 is on the API while at run time.  We are pointing to sandbox right now on dev.

1. When do you think your testing will be completed ?
2. Do you have any plan on creating a nuget instead of sdk ??

**Here is the stacktrace:** 
error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by brianarnold789** [comment]
@chandratokachichu It is not on our current road map to actively support .NET Core. I have, however, run a portability analysis on the solution (attached). Given that result, we would probably look to support .NET Core 2.0 in the future. [ApiPortAnalysis.xlsx](https://github.com/LitleCo/litle-sdk-for-dotNet/files/1128224/ApiPortAnalysis.xlsx) But, I don't currently have a time line for that.

We have a NuGet package: https://www.nuget.org/packages/Vantiv.LitleSdkForNet/ it is built for .NET 4.5

error CS0012 looks like a compilation issue? Are you getting as far as successfully building your project with the Vantiv dll? I am guessing the HTTP 500 comes from running a unit test or is this coming from a running application? Either way, can you send the raw XML request and response (enabled with the "printxml" flag) to sdksupport@vantiv.com for further help?
