### ISSUE TITLE
Support for async/await

### ISSUE THREAD

**Issue by DavidRogers** [LitleCo/litle-sdk-for-dotNet#49]
I would really like async support in this library, my company's API that consumes this is all async top to bottom and this is our only dependency that doesn't support async. I care enough to have taken the time to add it myself: https://github.com/Vantiv/litle-sdk-for-dotNet/pull/48
If there is anything else I can do to see this added, please let me know! Thanks!

**Comment by DavidRogers** [comment]
Just wondering when you plan on publishing a new release to get this change on nuget?

**Comment by brianarnold789** [comment]
@DavidRogers we'll have it published by the end of the week

**Comment by chahatSharma** [comment]
This change has been implemented in release 9.12.5 published on Nuget.

**Comment by DavidRogers** [comment]
I have added another [PR](https://github.com/Vantiv/litle-sdk-for-dotNet/pull/50) to bring this support to the 11.0 branch.

**Comment by DavidRogers** [comment]
@brianarnold789 Any word on if/when you can merge this?

**Comment by brianarnold789** [comment]
Hi @DavidRogers 
We will try to get to it this week

**Comment by DavidRogers** [comment]
@brianarnold789 That would be great, thanks!
