### ISSUE TITLE
Configuration setting "timeout" never used?

### ISSUE THREAD

**Issue by patrick-steele** [LitleCo/litle-sdk-for-dotNet#53]
I just went through the codebase and I can't see where the `timeout` configuration value is used. I can see it set in a bunch of places inside the configuration dictionary, but I'm not seeing it actually pulled out and used anywhere.

Is this setting still used?

**Comment by swapnilhande** [comment]
Timeout property is not used is the code anymore.

**Comment by tinmarin** [comment]
Hey guys, how can I increase the timeout if the property is not used?

**Comment by patrick-steele** [comment]
@tinmarin You could probably manually set it on the `HttpWebRequest` object created in `HttpPostCoreAsync` (Communications.cs).  Looks like all of the HTTP communications goes through that method.

**Comment by tinmarin** [comment]
@patrick-steele  The reason I was asking about the timeout setting is because I am getting this error "Unable to connect to the remote server". I thought maybe increasing the timeout will fix it, but it didn't. Have you ever experienced something like that?

**Comment by patrick-steele** [comment]
Is this in the test or a live environment? I think the test environment is
locked down via IP whitelisting (can't recall though -- it's been a while
since I last integrated with Vantiv).

**Comment by tinmarin** [comment]
It is the live environment. When I retry it goes through, but sometimes it takes a couple of tries. Thank you for the response though.

**Comment by swapnilhande** [comment]
You could use the method blockAndWaitForResponse to wait. 
```
string batchName = litle.sendToLitle();
litle.blockAndWaitForResponse(batchName, 12000);
litleResponse litleResponse = litle.receiveFromLitle(batchName);
```

**Comment by tinmarin** [comment]
@swapnilhande  Thank you, I will try that out
