### ISSUE TITLE
.NET Core 2.x support

### ISSUE THREAD

**Issue by DanielVukelich** [LitleCo/litle-sdk-for-dotNet#55]
Is there any plan to release a version of litle-sdk that is .NET Core compatible?  We are moving our systems to .NET Core, and this is one of the few packages that we use that does not have a .NET Core build.

I did a cursory examination, and it appears that the only part of your code that is not immediately compatible is your dependency on tamir-sharpssh, which is abandoned does not appear to have any .NET Core compatible ports.  However, if you were to find an alternative sftp library that is .NET Core compatible, it appears that the remainder of your code would be relatively simple to migrate.

**Comment by sesser** [comment]
Almost a year has passed and no response from Worldpay. Slow adoption is the name of the game; if it ain't broke, keep making money.

**Comment by FletcherTime** [comment]
.NET Core support is now available through a branch of our newer C# SDK, which can be found [here](https://github.com/Vantiv/cnp-sdk-for-dotnet/tree/12.x-net-core). However, we do not plan on making such support available for versions earlier than v12.7.
