### ISSUE TITLE
TLS v1 stop working after API calls

### ISSUE THREAD

**Issue by nithrous** [LitleCo/litle-sdk-for-dotNet#56]
I found that after using this SDK `ServicePointManager.SecurityProtocol` set to `SecurityProtocolType.Tls11` and `SecurityProtocolType.Tls12` and app cannot work with `SecurityProtocolType.Tls`, I should enable it manually. Could you please fix that?

**Comment by swapnilhande** [comment]
Hi @nithrous
Vantiv has stopped supporting weaker security protocol TLS v1, which is why it has been removed from the SDK. We highly recommend you to upgrade your system to support the stronger protocol of TLS v1.2.

Thanks.

**Comment by nithrous** [comment]
@swapnilhande, 
It's good that SDK uses strong protocols of TLS but I also make API calls to another systems that requires TLS v1 and I should always manually enable TLS v1 after using vantiv SDK. I just suggest to reset `ServicePointManager.SecurityProtocol` after vantiv usage.
