### ISSUE TITLE
Incorrect sandbox URL in settings file

### ISSUE THREAD

**Issue by atuggle** [LitleCo/litle-sdk-for-dotNet#57]
Upon initial clone of this repository the URL in the settings file is incorrect for running tests so all the test fail:
https://github.com/Vantiv/litle-sdk-for-dotNet/blob/11.4.1/LitleSdkForNet/LitleSdkForNet/Properties/Settings.Designer.cs#L184

While reading this documentation: https://vantiv.github.io/sandbox/
I found this URL that works: https://www.testvantivcnp.com/sandbox/communicator/online

Also if you open the Settings in Visual Studio it updates the Settings.Designer.cs file and removes the following "Required" settings:
- useEncryption
- vantivPublicKeyId
- pgpPassphrase
- gnuPgDir

Sorry if this is not what you expected, as a new user I expected to clone and have it run the unit tests...

**Comment by Charmik-Sheth** [comment]
Thank you for letting us know. It has been fixed.
Please clone the latest code from https://github.com/Vantiv/litle-sdk-for-dotNet.git
It should not have any errors.
