### ISSUE TITLE
Timeout setting not honored for HttpPost calls

### ISSUE THREAD

**Issue by mynameismud** [LitleCo/litle-sdk-for-dotNet#58]
I cannot find any reference to the configuration setting for "timeout" within HttpPostCoreAsync.
It appears that the timeout config setting is only used within FtpPoll calls. 

Communications.cs, line 140 contains a hardcoded 8000ms value for the ServicePoint.MaxIdleTime setting, which is not the same thing anyway.

Also, after a lot of Googling, it looks like the HttpWebRequest class you are using does not respect the timeout settings anyway when you are using async methods. 

HttpPostCoreAsync may need a rework.

**Comment by mynameismud** [comment]
Any response here? 

We're having a small percentage of failed transactions every night that seem to be related to this issue.

**Comment by vivek42** [comment]
We have removed the timeout settings as .NET libraries override the values. Hence closing the issue.
